# Generated by Django 5.2.9 on 2026-01-09 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
