# Generated by Django 5.2.9 on 2026-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_casestudy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
