# Generated by Django 5.2.9 on 2026-01-09 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main image for the post', max_length=255, null=True, verbose_name='image'),
        ),
    ]
